In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("supply_chain_data.csv")
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [3]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [4]:
df.rename(columns={'SKU':'Product ID'},inplace=True)
df.drop('Availability',axis=1,inplace=True)
df.drop('Customer demographics',axis=1,inplace=True)
df.drop('Lead times',axis=1,inplace=True)
df.columns

Index(['Product type', 'Product ID', 'Price', 'Number of products sold',
       'Revenue generated', 'Stock levels', 'Order quantities',
       'Shipping times', 'Shipping carriers', 'Shipping costs',
       'Supplier name', 'Location', 'Lead time', 'Production volumes',
       'Manufacturing lead time', 'Manufacturing costs', 'Inspection results',
       'Defect rates', 'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [5]:
df.tail()

,Product type,Product ID,Price,Number of products sold,Revenue generated,Stock levels,Order quantities,Shipping times,Shipping carriers,Shipping costs,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
95,haircare,SKU95,77.903927,672,7386.363944,15,26,9,Carrier B,8.630339,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,324,7698.424766,67,32,3,Carrier C,5.352878,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,62,4370.916580,46,4,9,Carrier A,7.904846,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,913,8525.952560,53,27,7,Carrier B,1.409801,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,627,9185.185829,55,59,6,Carrier B,1.311024,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   Product ID               100 non-null    object
 2   Price                    100 non-null    float64
 3   Number of products sold  100 non-null    int64
 4   Revenue generated        100 non-null    float64
 5   Stock levels             100 non-null    int64
 6   Order quantities         100 non-null    int64
 7   Shipping times           100 non-null    int64
 8   Shipping carriers        100 non-null    object
 9   Shipping costs           100 non-null    float64
 10  Supplier name            100 non-null    object
 11  Location                 100 non-null    object
 12  Lead time                100 non-null    int64
 13  Production volumes       100 non-null    int64
 14  Manufacturing lead time  100 non-null    int64
 15  Manufacturing costs      100 non-null    float64
 16  Inspection results       100 non-null    object
 17  Defect rates             100 non-null    float64
 18  Transportation modes     100 non-null    object
 19  Routes                   100 non-null    object
 20  Costs                    100 non-null    float64
dtypes: float64(6), int64(7), object(8)
memory usage: 16.5+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   Product ID               100 non-null    object
 2   Price                    100 non-null    float64
 3   Number of products sold  100 non-null    int64
 4   Revenue generated        100 non-null    float64
 5   Stock levels             100 non-null    int64
 6   Order quantities         100 non-null    int64
 7   Shipping times           100 non-null    int64
 8   Shipping carriers        100 non-null    object
 9   Shipping costs           100 non-null    float64
 10  Supplier name            100 non-null    object
 11  Location                 100 non-null    object
 12  Lead time                100 non-null    int64
 13  Production volumes       100 non-null    int64
 14  Manufacturing lead time  100 non-null    int64
 15  Manufacturing costs      100 non-null    float64
 16  Inspection results       100 non-null    object
 17  Defect rates             100 non-null    float64
 18  Transportation modes     100 non-null    object
 19  Routes                   100 non-null    object
 20  Costs                    100 non-null    float64
dtypes: float64(6), int64(7), object(8)
memory usage: 16.5+ KB

In [9]:
df.describe()

,Price,Number of products sold,Revenue generated,Stock levels,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,460.990000,5776.048187,47.770000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,303.780074,2732.841744,31.369372,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,8.000000,1061.618523,0.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,184.250000,2812.847151,16.750000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,392.500000,6006.352023,47.500000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,704.250000,8253.976921,73.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,996.000000,9866.465458,100.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [10]:
numeric_cols = df.select_dtypes(include='number').columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_count = ((df[col] < lower) | (df[col] > upper)).sum()

    print(col, ":", outlier_count)

Price : 0
Number of products sold : 0
Revenue generated : 0
Stock levels : 0
Order quantities : 0
Shipping times : 0
Shipping costs : 0
Lead time : 0
Production volumes : 0
Manufacturing lead time : 0
Manufacturing costs : 0
Defect rates : 0
Costs : 0

In [11]:
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

load_dotenv()

username = os.getenv("DB_USERNAME")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [13]:
table_name = 'Data'

df.to_sql(table_name, engine, if_exists='replace', index=False)

100

In [17]:
#Converting df to csv for using it in tableau
df.to_csv("supply_chain_cleaned.csv", index=False)